### ISSUE TITLE
Removal of mdl_question column "category" causes type_combined to fail in Moodle 4.0

### ISSUE THREAD

**Issue by brianortner** [moodleou/moodle-qtype_combined#8]
The following causes a dml exception:

Code: 
    public static function get_subq_data_from_db($questionid, $getoptions = false) {
        global $DB;
        $sql = 'SELECT q.*, qc.contextid FROM {question} q '.
            'JOIN {question_categories} qc ON q.category = qc.id ' .
            'WHERE q.parent = $1';

        // Load the questions.
        if (!$subqrecs = $DB->get_records_sql($sql, array($questionid))) {
            return array();
        }
        if ($getoptions) {
            get_question_options($subqrecs);
        }
        return $subqrecs;
    }

**Comment by timhunt** [comment]
It is a known issue that qtype_combined has not been updated to support Moodle 4.0. We don't need another duplicate.
